### ISSUE TITLE
Build - The project does not build with babel 6.8.0

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-center#604]
Steps to repeat:
1.  rm node_modules
2.  npm install
3.  npm run build

Results in:
ERROR in (0 , _typeof3.default) is not a function

**Comment by SOAP1914** [comment]
build for me 👍  
<img width="789" alt="screen shot 2016-05-04 at 11 26 10 am" src="https://cloud.githubusercontent.com/assets/10637320/15019207/1e219abe-11eb-11e6-9890-bfcacfb27537.png">

@clarkjefcoat
